#ifndef GAME_CONSTANTS
#define GAME_CONSTANTS



#define BUTTON_ID_INTRO 0x01

#define BUTTON_ID_SALIR 0x02
#define BUTTON_ID_PERSONAJE 0x03
#define BUTTON_ID_JUGAR 0x04
#define BUTTON_ID_BORRAR 0x05
#define BUTTON_ID_ATRAS 0x06
#define BUTTON_ID_GUARDAR 0x07
#define BUTTON_ID_CANCELAR 0x08
#define BUTTON_ID_NUEVO 0x09
#define BUTTON_ID_OPCIONES 0x10





#ifndef TRIGO
#define TRIGO
#define TORADIANS(x) x*(3.1419/180)
#define TODEGREES(x) x*(180/3.1419)
#endif

#define BASE_LIFEBAR_WIDTH 100


// View options

#define VIEW_WIDTH 1024
#define VIEW_HEIGHT 768

#define WORLD_UPPER_BOUND -250
#define WORLD_DOWN_BOUND VIEW_HEIGHT+250
#define WORLD_LEFT_BOUND -250
#define WORLD_RIGHT_BOUND VIEW_WIDTH+250

#define WORLD_WIDTH WORLD_RIGHT_BOUND - WORLD_LEFT_BOUND
#define WORLD_HEIGHT WORLD_DOWN_BOUND - WORLD_UPPER_BOUND

// Profundity options

#define MAX_Y 735
#define MAX_Z 235

#define SCREEN_X(x, z)		(x + ((512-x) * (z /MAX_Z) * 0.35))
#define SCREEN_Y(y, z)		(y - 0.8*z)

#define PROFUNDITY_SIZE 80
#define PROFUNDITY_HIT_RADIUS 20
// #define PROFUNDITY_BOUND (WORLD_HEIGHT-PROFUNDITY)
#define GET_SCALE(z)  (1.1f - 0.40*(z/MAX_Z) )

#define CHAR_SPEED_BASE_X 350
#define CHAR_SPEED_BASE_Z 150

// ENEMY IDS
#define ID_PULPO 0x1001
#define ID_CALAMAR 0x1002

// ENEMY CAST IDS
#define ID_ROCKET 0x2001


#define ID_CHARACTER 0x3000
#define ID_FRUIT 0x4000


// FRUIT IDS
#define ID_APPLE_NORMAL 100
#define ID_APPLE_UPGRADE1 101
#define ID_APPLE_UPGRADE2 102
#define ID_APPLE_UPGRADE3 103


// SEQUENCE IDS (Can repeat between different objects)

#define ID_SEQUENCE_NORMAL 0x01

#define ID_SEQUENCE_PULPO_NORMAL 0x01
#define ID_SEQUENCE_PULPO_CATCHINGHEAD 0x02

#define ID_SEQUENCE_MONOSMALL_NORMAL 0x01

#define ID_SEQUENCE_GUY_NORMAL 0x01
#define ID_SEQUENCE_GUY_NORMAL_WALKING 0x11
#define ID_SEQUENCE_GUY_LSHOT 0x02
#define ID_SEQUENCE_GUY_RSHOT 0x03
#define ID_SEQUENCE_GUY_DOUBLESHOT 0x04



// Collision types

#define ID_COLLISION_ENEMY_CHARACTERCAST 0x01
#define ID_COLLISION_ENEMY_CHARACTER 0x02
#define ID_COLLISION_ENEMY_ENEMY 0x03

// BASE MOVE SPEEDS (pixels/second)

#define PULPO_Y_SPEED 150
#define PULPO_WALK_SPEED 120
#define PULPO_TOTALDAMAGE 50
#define PULPO_STUNTIME 1.5f
#define PULPO_DPS PULPO_TOTALDAMAGE/PULPO_STUNTIME

#define MONO_WALK_SPEED 50
#define MONO_Y_SPEED 50
#define MONO_X_SPEED 20

#define MONO_DAMAGE 50

#define MONOSMALL_DAMAGE 25
#define MONOSMALL_HP 100

#define BULLET_SPEED  230
#define BASE_HANDGUN_DELAY 1

#define ROCKET_ACCELERATION 500
#define ROCKET_MAX_SPEED 300
#define ROCKET_RANGE_RADIUS 300

// Profundities
#define CAST_RELATIVE_PROFUNDITY +2 // Relative to character.
#define WEAPON_RELATIVE_PROFUNDITY -1



// Level / ambient

#define MIN_AMBIENT_EVENT_DELAY 2
#define MAX_AMBIENT_EVENT_DELAY 25


#endif
